from sqlalchemy.orm import Session
from db import Book
import os

def compile_book(session: Session, book_id: int):
    """Compiles all chapters into a single file."""
    book = session.get(Book, book_id)
    if not book:
        return

    # Check if all chapters are approved
    # (In loose mode, we might allow compiling drafts, but let's be strict for now or warn)
    
    filename = f"{book.title.replace(' ', '_')}_Final.txt"
    filepath = os.path.join(os.getcwd(), filename)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(f"Title: {book.title}\n")
        f.write("Generated by AI Book Agent\n")
        f.write("="*30 + "\n\n")
        
        # Write Outline
        if book.outline:
            f.write("OUTLINE\n")
            f.write(book.outline.content)
            f.write("\n\n" + "="*30 + "\n\n")
        
        # Write Chapters
        for ch in book.chapters:
            f.write(f"CHAPTER {ch.chapter_number}: {ch.title}\n")
            f.write("-" * 20 + "\n")
            f.write(ch.content if ch.content else "[No Content]")
            f.write("\n\n" + "#" * 10 + "\n\n")
            
    book.status = "COMPLETED"
    session.commit()
    
    print(f"Book compiled successfully to: {filepath}")
    return filepath
